export default {
  CREATE_USER_SUCCESS: "user created successfully",
  CREATE_USER_FAILED: "Failed to create user",
  GET_ALL_USER_SUCCESS: "All users fetched successfully",
  GET_ALL_USER_FAILED: "Failed to fetch all users",
  GET_ALL_USER_COUNT_SUCCESS: "All users count fetched successfully",
  GET_ALL_USER_COUNT_FAILED: "Failed to fetch all users count",
  LOGIN_SUCCESS: "loggedin successfully",
  CREATE_PROFILE_SUCCESS: "User profile created successfully",
  CREATE_PROFILE_FAILED: "Failed to create user profile",
  UPDATE_PROFILE_SUCCESS: "User profile updated successfully",
  UPDATE_PROFILE_FAILED: "Failed to update user profile",
  GET_PROFILE_SUCCESS: "User profile fetched successfully",
  GET_PROFILE_FAILED: "Failed to fetch user profile",
  PROFILE_NOT_FOUND: "User profile not found",
  PROFILE_ALREADY_EXISTS: "User profile already exists",
};
